title: "Game submission"
labels: ["Game submission"]
body:
  - type: input
    id: Name
    attributes:
      label: 🎮 Game Name
      description: Insert the name of your game.
    validations:
      required: true
  - type: input
    id: Description
    attributes:
      label: 📜 Game Description
      description: Provide a quick summary of your game, including its theme, objectives, and any unique features.
    validations:
      required: true
  - type: input
    id: repository
    attributes:
      label: 🏷️ Repository Name
      description: Provide the name of your game's repository.
    validations:
      required: true  
  - type: textarea
    id: copilot
    attributes:
      value: |
        # 🤖 How I've Used GitHub Copilot
        <!-- Describe how GitHub Copilot assisted in your development process, e.g.:
        - Generating reusable Phaser functions.
        - Suggesting sprite animations or physics configurations.
        - Speeding up coding for game states, player mechanics, or AI behaviors.
        - Helping debug or refactor Phaser code snippets. -->
